### ISSUE TITLE
How can I mock a property initialised in the class constructor?

### ISSUE THREAD

**Issue by filipecorrea** [omermorad/automock#33]
Is it possible to mock a property that is initialised in the class constructor?

This is the controller that I want to test:

```typescript
import { Controller, Get } from '@nestjs/common'
import { LoggerAdapter } from '../infrastructure/adapters/logger.adapter'
import { routesV1 } from '../infrastructure/configs/app.routes'
import { Logger } from '../libs/ddd/domain/ports/logger.port'

@Controller(routesV1.version)
class HealthHTTPController {
  private readonly logger: Logger

  constructor (
    loggerAdapter: LoggerAdapter
  ) {
    this.logger = loggerAdapter.getLogger(this.constructor.name)
  }

  @Get(routesV1.health.get)
  get (): void {
    this.logger.info('Health check')
  }
}

export { HealthHTTPController }
```

Logger interface:

```typescript
interface Logger {
  trace(obj: unknown, msg?: string, ...args: any[]): void
  trace(msg: string, ...args: any[]): void
  debug(obj: unknown, msg?: string, ...args: any[]): void
  debug(msg: string, ...args: any[]): void
  info(obj: unknown, msg?: string, ...args: any[]): void
  info(msg: string, ...args: any[]): void
  warn(obj: unknown, msg?: string, ...args: any[]): void
  warn(msg: string, ...args: any[]): void
  error(obj: unknown, msg?: string, ...args: any[]): void
  error(msg: string, ...args: any[]): void
  child(obj: unknown, options?: unknown): Logger
}

export { Logger }
```

The test:

```typescript
import { TestBed } from '@automock/jest'
import { LoggerAdapter } from '../../src/infrastructure/adapters/logger.adapter'
import { HealthHTTPController } from '../../src/interface/health.http.controller'

describe('HealthHTTPController', () => {
  let healthHTTPController: HealthHTTPController
  let loggerAdapter: jest.Mocked<LoggerAdapter>

  beforeAll(() => {
    const { unit, unitRef } = TestBed.create(HealthHTTPController).compile()

    healthHTTPController = unit
    loggerAdapter = unitRef.get(LoggerAdapter)
    console.log(healthHTTPController) // HealthHTTPController { logger: undefined }
  })

  describe('get', () => {
    it('logs', async () => {
      expect(await healthHTTPController.get()).toReturn()
    })
  })
})
```

The error:

```bash
FAIL test/unit/health.http.controller.spec.ts
HealthHTTPController
  get
    ✕ logs (1 ms)

● HealthHTTPController › get › logs

  TypeError: Cannot read properties of undefined (reading 'info')

    17 |   @Get(routesV1.health.get)
    18 |   get (): void {
  > 19 |     this.logger.info('Health check')
       |                 ^
    20 |   }
    21 | }
    22 |

    at HealthHTTPController.get (src/interface/health.http.controller.ts:19:17)
    at Object.<anonymous> (test/unit/health.http.controller.spec.ts:19:41)
```

**Comment by omermorad** [comment]
Hi @filipecorrea,
In order for `automock` to properly reflect the class dependencies, the `Logger` must be injected into the class constructor, and not as a property. Why are you using `loggerAdapter: LoggerAdapter` as a parameter instead of using it as a property?

**Comment by filipecorrea** [comment]
I'm injecting it as a parameter because `LoggerAdapter` is a singleton implementation for the `Logger` interface:

**LoggerAdapter**

```typescript
import { Injectable } from '@nestjs/common'
import pino from 'pino'
import { config } from '../../infrastructure/configs/logger.config'
import { Logger } from '../../libs/ddd/domain/ports/logger.port'

@Injectable()
class LoggerAdapter {
  getLogger(name?: string): Logger {
    const logger = pino({
      ...config,
      transport: config.pretty
        ? {
          target: 'pino-pretty',
          options: {
            colorize: true,
            singleLine: true
          }
        }
        : undefined,
      timestamp: pino.stdTimeFunctions.isoTime
    })

    return name === undefined
      ? logger
      : logger.child({ name })
  }
}

export { LoggerAdapter }
```

**LoggerAdapterModule**

```typescript
import { Global, Module } from '@nestjs/common'
import { LoggerAdapter } from '../../infrastructure/adapters/logger.adapter'

const singleton = new LoggerAdapter()
const singletonProvider = {
  provide: LoggerAdapter,
  useFactory: () => singleton
}

@Global()
@Module({
  providers: [singletonProvider],
  exports: [LoggerAdapter]
})
class LoggerAdapterModule { }

export { LoggerAdapterModule }
```

I know it might not be an issue with your library, which is great btw, but you haven't activated the "discussions" for this repo and I wanted to discuss the topic with you.

**Comment by omermorad** [comment]
Thank you! Okay, it's clearer now. Instead of utilizing the `LoggerAdapter` injectable class, you should utilize a dynamic provider (factory provider?). Thank you for drawing my notice to the discussions section, it is now open for some :)
